sudo: required
services:
    - docker

before_install:
    - docker build -t skpradeep/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run skpradeep/react-test npm test -- -- coverage

after_success:
    - docker build -t skpradeep/multi-client ./client
    - docker build -t skpradeep/multi-nginx  ./nginx
    - docker build -t skpradeep/multi-worker ./worker
    - docker build -t skpradeep/multi-server ./server

# login in to docker cli
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin



